### PR TITLE
Add react starter files and folder structure

### PR DESCRIPTION
**Pull request by promiseNwafor**

### CODE REVIEW

**Comment by Snowwhite-Workshop** [comment]
good so far.. go ahead and create the structure.. 
in src >> components >> atoms, molecules and organisms
create those folders

**Comment by chuksdozie** [comment]
good so far.. go ahead and create the structure..
in src >> components >> atoms, molecules and organisms
create those folders

**Comment by chuksdozie** [comment]
for now I will merge this.. so after you create those folders, create another PR.

**Review by chuksdozie — COMMENTED** [review]
These are the React Starter files.. work on  the folder structure and create another PR.

**Pull request merged**
